# Generated by Django 5.2.10 on 2026-01-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='title',
            new_name='curso',
        ),
    ]
