# Generated by Django 5.2.10 on 2026-01-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_rename_title_curso_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='curso',
            new_name='title',
        ),
    ]
